{% set name = "foam_ct_phantom" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmpelt/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f08884c6b375cb1602d0339142dca7791ea256de4025ef7fe38cf879e6cf74e0

build:
  number: 0
  skip: true  # [win and py<36]
  script: {{ PYTHON }} -m pip install . -vv  # [linux]
  script: {{ PYTHON }} setup.py bdist_wheel --plat-name macosx-10.9-x86_64 && pip install --no-index --find-links=dist foam_ct_phantom  # [osx]
  script: {{ PYTHON }} -m pip install . -vv --install-option=--generator --install-option="NMake Makefiles"  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - setuptools
    - scikit-build
    - openmp
    - pip
  run:
    - python
    - numpy
    - scipy
    - tqdm
    - h5py
    - psutil
    - numba
    - sortedcollections
    - openmp
    - pathlib2

test:
  imports:
    - foam_ct_phantom

about:
  home: http://github.com/dmpelt/foam_ct_phantom
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for generating foam-like phantoms for CT.

  description: |
    A Python package for generating foam-like phantoms for CT.
  doc_url: http://dmpelt.github.io/foam_ct_phantom
  dev_url: https://github.com/dmpelt/foam_ct_phantom

extra:
  recipe-maintainers:
    - dmpelt
