travis:
  secure:
    BINSTAR_TOKEN: TENbxPApNXCjqvcCYFH0ekQD1LdvcWbn+HapJG1k6mHY1qttTYQUHxlJfwBxpx6XxK01Pmp8DkjhXgQWR6gyJac3EEQ9356P9Pv0BpTLvvMyIprqopfCYzilsDMlqXQbDjbVPiRBbRzq+t6UurHCQHkDY8D0wcPcv9y3sFLCJD1oBnCL2DruTxVUxW6qGeqrujVuYIP2v0uF2HlAe8L2BCjAcGfzT3Kqk6zvIqn89RHa+LJH3wRKrJwTTXDhqeHuu/BFg8Lc4qjDVooMahZqSDpuPOC62NxEXE7io1DITj/fMoZvgkokR12fcYqJXbCGTqY7l0jjxdxmOqnUT1q8AUVOvOxn5r7DcRjhuHXlAkzRNajnq7409JsBSJpDfM9lCY9DN1BCKxhQpJbjqO5C9zu0xQXV0W2TZwOan6YgmANCWVawVIDH0ufc44yHB/bjYwMUue/4fYjmIv/hrIUx9ndXpOV1ISA2PnfewmMXLnV8QWNPqSbwQGhHqUuon/mXHxYN24tzUzCjp06WNjVQAuT9exLRk9B/fK6ArQgzhe9jF55/PxL+O9Z430GkNRkZL2xhoouXkfIAcShEKAfwWbJSczyc7nL/KHWzbNVJRtwU2MtJGw8mh9lPRtrD3R8LRipcVWuvLErLYS3dJbDyZA5fjyQ1rvKJbV91MTWnHsY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
